name: taisei-build-tests
on:
  push:
    branches:
      - master
      - v1.*
      - switch-ci
    tags:
      - v1.*
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"

jobs:
  switch-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Build Tools (pip)
        run: pip install meson ninja zstandard

      - name: Install Build Tools (apt)
        run: sudo apt update && sudo apt install python3-docutils

      - name: Env - Step 1 (Crossfile)
        run: |
          mkdir -p ./build
          ./switch/crossfile.sh > ./build/crossfile.txt

      - name: Configure - Step 2 (Meson)
        run: meson setup build/ --cross-file="./build/crossfile.txt" -Db_lto=false -Dstrip=false -Ddeprecation_warnings=no-error -Dwerror=true -Db_pch=false

      - name: Build - Step 3 (Ninja)
        run: meson compile -C build/
